#!/usr/bin/env bash
# File: autobrr-irc-anti-flap.sh
# Project role: Persistent state-machine watchdog that minimizes autobrr IRC connect/disconnect flapping.
# Project flow: systemd launches this file; this file sources the dotenv configuration, restores persistent
# state, observes Docker and autobrr APIs, confirms failures only after initialization, stops autobrr once,
# records a full cooldown from every observed running-to-stopped transition, and starts autobrr only after
# that cooldown has expired.
#
# Direct inputs:
# - AUTOBRR_ANTI_FLAP_ENV: optional absolute path string for the dotenv file; defaults to
#   /etc/autobrr-irc-anti-flap.env. Used by load_config.
# - Configuration entries documented individually in autobrr-irc-anti-flap.env.example. Used by
#   load_config and the functions named in that file.
# - Docker inspection output for AUTOBRR_CONTAINER: running boolean and container existence. Used by
#   container_is_running and container_exists.
# - GET /api/healthz/readiness: bounded HTTP response whose trimmed body must be OK. Used by collect_health.
# - GET /api/irc: JSON array of IRC network objects. Enabled networks and their connected, healthy,
#   channels[].enabled, channels[].monitoring, and channels[].state fields are used by collect_health.
# - STATE_FILE: shell-escaped internal state generated by save_state. Used by load_state.
#
# Direct outputs and side effects:
# - Timestamped key/value log lines on stdout/stderr for systemd-journald, produced by log.
# - Atomic mode-0600 STATE_FILE updates, produced by save_state.
# - docker stop AUTOBRR_CONTAINER only after an initialized, confirmed stop condition, produced by
#   stop_and_begin_cooldown.
# - docker start AUTOBRR_CONTAINER only when a recorded cooldown has expired and the container remains
#   stopped, produced by start_after_expired_cooldown.
#
# Top-level state variables:
# - INITIALIZED: 1 only after readiness is OK, the IRC API is valid, and at least one enabled network is
#   connected; reset to 0 whenever a stop is observed or a start occurs.
# - LAST_RUNNING: previous observed Docker running state, used to detect both user and watchdog stops.
# - COOLDOWN_UNTIL_EPOCH: Unix epoch deadline created at stop detection; 0 means no active cooldown.
# - CONSECUTIVE_FAILURES and FIRST_FAILURE_EPOCH: debounce state for qualifying stop conditions.
# - LAST_REASON: diagnostic string describing the latest qualifying failure or stop.
#
# Functions:
# - log: receives severity and key/value text; emits one timestamped log line.
# - require_commands: receives no arguments; exits if a required executable is unavailable.
# - load_config: sources and validates the dotenv file; normalizes AUTOBRR_URL.
# - load_state: restores state variables from STATE_FILE when readable.
# - save_state: atomically serializes all state variables to STATE_FILE.
# - container_exists: returns success when Docker can inspect AUTOBRR_CONTAINER.
# - container_is_running: returns success only when Docker reports the container running.
# - api_get: receives an API path; emits the bounded authenticated HTTP response body.
# - collect_health: receives no arguments; populates readiness and IRC aggregate globals.
# - clear_failures: resets debounce counters and the latest failure reason.
# - begin_cooldown: receives current epoch and reason; records a full cooldown from that time.
# - observe_stopped: handles a stopped container, detects a new stop, and starts only after expiry.
# - stop_and_begin_cooldown: receives epoch and reason; stops a running container and records cooldown.
# - evaluate_running: receives epoch; establishes initialization and evaluates confirmed stop conditions.
# - main: validates dependencies/configuration, locks singleton execution, and runs the polling loop.

set -Eeuo pipefail

ENV_FILE="${AUTOBRR_ANTI_FLAP_ENV:-/etc/autobrr-irc-anti-flap.env}"
INITIALIZED=0
LAST_RUNNING=-1
COOLDOWN_UNTIL_EPOCH=0
CONSECUTIVE_FAILURES=0
FIRST_FAILURE_EPOCH=0
LAST_REASON=""

log() {
  local level="$1"
  shift
  printf '%s level=%s %s\n' "$(date --iso-8601=seconds)" "$level" "$*"
}

require_commands() {
  local name
  for name in curl jq docker flock date sleep mktemp mv chmod mkdir dirname; do
    command -v "$name" >/dev/null 2>&1 || {
      log error "event=missing_dependency command=$name"
      exit 1
    }
  done
}

load_config() {
  [[ -r "$ENV_FILE" ]] || {
    log error "event=config_unreadable path=$ENV_FILE"
    exit 1
  }

  set -a
  source "$ENV_FILE"
  set +a

  local required
  for required in AUTOBRR_URL AUTOBRR_API_TOKEN AUTOBRR_CONTAINER STATE_FILE LOCK_FILE POLL_INTERVAL_SECONDS HTTP_TIMEOUT_SECONDS COOLDOWN_SECONDS FAILURE_CONFIRMATIONS FAILURE_WINDOW_SECONDS BAD_NETWORK_MINIMUM BAD_NETWORK_PERCENT; do
    [[ -n "${!required:-}" ]] || {
      log error "event=missing_config key=$required"
      exit 1
    }
  done

  local numeric value
  for numeric in POLL_INTERVAL_SECONDS HTTP_TIMEOUT_SECONDS COOLDOWN_SECONDS FAILURE_CONFIRMATIONS FAILURE_WINDOW_SECONDS BAD_NETWORK_MINIMUM BAD_NETWORK_PERCENT; do
    value="${!numeric}"
    [[ "$value" =~ ^[0-9]+$ ]] || {
      log error "event=invalid_integer key=$numeric value=$value"
      exit 1
    }
  done

  (( POLL_INTERVAL_SECONDS > 0 && HTTP_TIMEOUT_SECONDS > 0 && COOLDOWN_SECONDS > 0 && FAILURE_CONFIRMATIONS > 0 && FAILURE_WINDOW_SECONDS > 0 && BAD_NETWORK_MINIMUM > 0 )) || {
    log error "event=invalid_nonpositive_config"
    exit 1
  }
  (( BAD_NETWORK_PERCENT >= 1 && BAD_NETWORK_PERCENT <= 100 )) || {
    log error "event=invalid_percentage key=BAD_NETWORK_PERCENT value=$BAD_NETWORK_PERCENT"
    exit 1
  }

  AUTOBRR_URL="${AUTOBRR_URL%/}"
}

load_state() {
  if [[ -r "$STATE_FILE" ]]; then
    source "$STATE_FILE"
  fi
}

save_state() {
  local directory temporary
  directory="$(dirname "$STATE_FILE")"
  mkdir -p "$directory"
  temporary="$(mktemp "${STATE_FILE}.tmp.XXXXXX")"
  {
    printf 'INITIALIZED=%q\n' "$INITIALIZED"
    printf 'LAST_RUNNING=%q\n' "$LAST_RUNNING"
    printf 'COOLDOWN_UNTIL_EPOCH=%q\n' "$COOLDOWN_UNTIL_EPOCH"
    printf 'CONSECUTIVE_FAILURES=%q\n' "$CONSECUTIVE_FAILURES"
    printf 'FIRST_FAILURE_EPOCH=%q\n' "$FIRST_FAILURE_EPOCH"
    printf 'LAST_REASON=%q\n' "$LAST_REASON"
  } > "$temporary"
  chmod 0600 "$temporary"
  mv -f "$temporary" "$STATE_FILE"
}

container_exists() {
  docker inspect "$AUTOBRR_CONTAINER" >/dev/null 2>&1
}

container_is_running() {
  [[ "$(docker inspect --format '{{.State.Running}}' "$AUTOBRR_CONTAINER" 2>/dev/null || true)" == "true" ]]
}

api_get() {
  local path="$1"
  curl --silent --show-error --fail --max-time "$HTTP_TIMEOUT_SECONDS" \
    --header "X-API-Token: $AUTOBRR_API_TOKEN" \
    "$AUTOBRR_URL$path"
}

collect_health() {
  local readiness_body irc_body parsed
  READINESS_OK=0
  IRC_API_OK=0
  ENABLED_NETWORKS=0
  CONNECTED_NETWORKS=0
  BAD_NETWORKS=0
  BAD_NETWORK_NAMES=""

  if readiness_body="$(api_get '/api/healthz/readiness' 2>/dev/null)"; then
    readiness_body="${readiness_body//$'\r'/}"
    readiness_body="${readiness_body//$'\n'/}"
    [[ "$readiness_body" == "OK" ]] && READINESS_OK=1
  fi

  if ! irc_body="$(api_get '/api/irc' 2>/dev/null)"; then
    return 0
  fi

  if ! parsed="$(jq -er '
    if type != "array" then error("IRC response is not an array") else . end
    | [ .[] | select(.enabled == true) ] as $enabled
    | [ $enabled[] | select(.connected == true) ] as $connected
    | [ $enabled[]
        | [ .channels[]? | select(.enabled == true) ] as $enabled_channels
        | select(
            (.connected != true)
            or (.healthy != true)
            or (($enabled_channels | length) > 0 and
                ([$enabled_channels[] | select(.monitoring == true and .state == "Monitoring")] | length) == 0)
          )
      ] as $bad
    | [
        ($enabled | length),
        ($connected | length),
        ($bad | length),
        ($bad | map((.id | tostring) + ":" + .name) | join(","))
      ]
    | @tsv
  ' <<< "$irc_body" 2>/dev/null)"; then
    return 0
  fi

  IFS=$'\t' read -r ENABLED_NETWORKS CONNECTED_NETWORKS BAD_NETWORKS BAD_NETWORK_NAMES <<< "$parsed"
  IRC_API_OK=1
}

clear_failures() {
  CONSECUTIVE_FAILURES=0
  FIRST_FAILURE_EPOCH=0
  LAST_REASON=""
}

begin_cooldown() {
  local now="$1" reason="$2"
  COOLDOWN_UNTIL_EPOCH=$((now + COOLDOWN_SECONDS))
  INITIALIZED=0
  LAST_RUNNING=0
  clear_failures
  LAST_REASON="$reason"
  save_state
  log warning "event=cooldown_started reason=$reason duration_seconds=$COOLDOWN_SECONDS cooldown_until_epoch=$COOLDOWN_UNTIL_EPOCH"
}

start_after_expired_cooldown() {
  local now="$1"
  if docker start "$AUTOBRR_CONTAINER" >/dev/null; then
    INITIALIZED=0
    LAST_RUNNING=1
    COOLDOWN_UNTIL_EPOCH=0
    clear_failures
    save_state
    log notice "event=container_started reason=cooldown_expired"
  else
    log error "event=container_start_failed reason=cooldown_expired"
  fi
}

observe_stopped() {
  local now="$1"

  if (( LAST_RUNNING != 0 )); then
    begin_cooldown "$now" "stop_observed"
    return 0
  fi

  if (( COOLDOWN_UNTIL_EPOCH == 0 )); then
    begin_cooldown "$now" "stopped_without_active_cooldown"
    return 0
  fi

  if (( now >= COOLDOWN_UNTIL_EPOCH )); then
    start_after_expired_cooldown "$now"
  else
    log info "event=cooldown_wait container=stopped remaining_seconds=$((COOLDOWN_UNTIL_EPOCH - now))"
  fi
}

stop_and_begin_cooldown() {
  local now="$1" reason="$2"

  container_is_running || return 0
  log warning "event=container_stop_requested reason=$reason confirmations=$CONSECUTIVE_FAILURES"
  if docker stop "$AUTOBRR_CONTAINER" >/dev/null; then
    begin_cooldown "$now" "$reason"
  else
    log error "event=container_stop_failed reason=$reason"
  fi
}

evaluate_running() {
  local now="$1" failure=0 reason="" bad_percent=0

  LAST_RUNNING=1
  collect_health

  if (( INITIALIZED == 0 )); then
    clear_failures
    if (( READINESS_OK == 1 && IRC_API_OK == 1 && ENABLED_NETWORKS > 0 && CONNECTED_NETWORKS > 0 )); then
      INITIALIZED=1
      save_state
      log notice "event=initialization_complete enabled_networks=$ENABLED_NETWORKS connected_networks=$CONNECTED_NETWORKS"
    else
      save_state
      log info "event=initializing readiness=$READINESS_OK irc_api=$IRC_API_OK enabled_networks=$ENABLED_NETWORKS connected_networks=$CONNECTED_NETWORKS"
    fi
    return 0
  fi

  if (( ENABLED_NETWORKS > 0 )); then
    bad_percent=$((BAD_NETWORKS * 100 / ENABLED_NETWORKS))
  fi

  if (( READINESS_OK == 0 )); then
    failure=1
    reason="readiness_not_ok"
  elif (( IRC_API_OK == 1 && BAD_NETWORKS >= BAD_NETWORK_MINIMUM && bad_percent >= BAD_NETWORK_PERCENT )); then
    failure=1
    reason="multiple_enabled_networks_bad_${BAD_NETWORKS}_of_${ENABLED_NETWORKS}"
  fi

  if (( failure == 0 )); then
    if (( CONSECUTIVE_FAILURES > 0 )); then
      log notice "event=failure_cleared previous_confirmations=$CONSECUTIVE_FAILURES"
    fi
    clear_failures
    save_state
    return 0
  fi

  if (( FIRST_FAILURE_EPOCH == 0 || now - FIRST_FAILURE_EPOCH > FAILURE_WINDOW_SECONDS )); then
    FIRST_FAILURE_EPOCH="$now"
    CONSECUTIVE_FAILURES=1
  else
    CONSECUTIVE_FAILURES=$((CONSECUTIVE_FAILURES + 1))
  fi
  LAST_REASON="$reason"
  save_state
  log warning "event=stop_condition_observed reason=$reason confirmation=$CONSECUTIVE_FAILURES required=$FAILURE_CONFIRMATIONS readiness=$READINESS_OK irc_api=$IRC_API_OK enabled_networks=$ENABLED_NETWORKS connected_networks=$CONNECTED_NETWORKS bad_networks=$BAD_NETWORKS bad_percent=$bad_percent affected=$BAD_NETWORK_NAMES"

  if (( CONSECUTIVE_FAILURES >= FAILURE_CONFIRMATIONS )); then
    stop_and_begin_cooldown "$now" "$reason"
  fi
}

main() {
  require_commands
  load_config
  mkdir -p "$(dirname "$LOCK_FILE")"
  exec 9>"$LOCK_FILE"
  flock -n 9 || {
    log error "event=already_running lock=$LOCK_FILE"
    exit 1
  }

  container_exists || {
    docker compose -f "$AUTOBRR_COMPOSE_FILE" up --no-start
    if [ $? -ne 0 ]; then
      log error "event=container_could_not_build compose-file=$AUTOBRR_COMPOSE_FILE"
      exit 1
    fi
  }

  load_state

  while true; do
    local now
    now="$(date +%s)"
    if container_is_running; then
      evaluate_running "$now"
    else
      observe_stopped "$now"
    fi
    sleep "$POLL_INTERVAL_SECONDS"
  done
}

main "$@"
